import { useMemo, useState } from "react";
import { GitBranch, Minus, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ButtonGroup } from "@/components/ui/button-group";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PageContainer } from "@/components/PageContainer";
import { StageTaskList } from "@/components/warranty/StageProgress";
import { ActorChip } from "@/components/warranty/badges";
import { cn } from "@/lib/utils";
import { dateOnly } from "@/lib/warranty/format";
import {
  CASE_PLAN_VERSIONS,
  CONDITIONAL_STAGES,
  CURRENT_PLAN_VERSION,
  PRIMARY_STAGES,
  TERMINAL_STAGES,
} from "@/lib/warranty/casePlan";
import { CASE_RULES, PLAN_CHANGELOG, type CaseRule } from "@/lib/warranty/rules";
import type { StageDefinition } from "@/lib/warranty/types";

// The case plan as the coding agent produced it, and the rules the case agent
// reads at run time. Two tabs, because they answer different questions: the plan
// is what the work IS, the rules are what MOVES it.

function StageCard({ stage }: { stage: StageDefinition }) {
  return (
    <Card className="gap-3 p-5">
      <div>
        <span className="block text-base font-semibold">{stage.name}</span>
        <span className="mt-0.5 block text-xs text-muted-foreground">SLA: {stage.sla}</span>
      </div>
      <div className="border-t border-border pt-3">
        <span className="mb-2 block text-xs font-medium uppercase tracking-wide text-muted-foreground">
          Tasks
        </span>
        <StageTaskList stage={stage} />
      </div>
      <span className="text-xs text-muted-foreground">Owner · {stage.owner}</span>
    </Card>
  );
}

function RuleRow({ rule }: { rule: CaseRule }) {
  return (
    <tr className="border-b border-border/50 align-top last:border-0">
      <td className="py-2.5 pl-4 pr-3 text-muted-foreground">{rule.scope}</td>
      <td className="px-3 py-2.5 font-medium">{rule.element}</td>
      <td className="px-3 py-2.5">
        {rule.rule}
        {rule.autoGenerated && (
          <span className="ml-1.5 rounded bg-muted px-1 py-0.5 text-[10px] uppercase tracking-wide text-muted-foreground">
            auto
          </span>
        )}
        {rule.since === "v2" && (
          <span className="ml-1.5 rounded bg-info/15 px-1 py-0.5 text-[10px] font-medium uppercase tracking-wide text-info">
            v2
          </span>
        )}
      </td>
      <td className="px-3 py-2.5 text-muted-foreground">{rule.when}</td>
      <td className="px-3 py-2.5">
        {rule.if ? (
          <code className="rounded bg-muted px-1.5 py-0.5 text-xs">{rule.if}</code>
        ) : (
          <span className="text-muted-foreground">None</span>
        )}
      </td>
      <td className="px-3 py-2.5">{rule.then}</td>
      <td className="py-2.5 pl-3 pr-4 text-muted-foreground">{rule.authoredBy ?? "Unattributed"}</td>
    </tr>
  );
}

export function CasePlansPage() {
  const [search, setSearch] = useState("");
  const [scope, setScope] = useState<"all" | "v2">("all");
  const [zoom, setZoom] = useState(100);

  const rules = useMemo(() => {
    const query = search.trim().toLowerCase();
    return CASE_RULES.filter((r) => (scope === "v2" ? r.since === "v2" : true)).filter((r) =>
      query
        ? [r.scope, r.element, r.rule, r.when, r.if ?? "", r.then, r.authoredBy ?? ""]
            .join(" ")
            .toLowerCase()
            .includes(query)
        : true,
    );
  }, [search, scope]);

  const current = CASE_PLAN_VERSIONS.find((v) => v.version === CURRENT_PLAN_VERSION);

  return (
    <PageContainer>
      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 className="text-xl font-semibold">Case · Industrial Equipment Warranty Resolution</h1>
            <p className="text-sm text-muted-foreground">
              Case plan {CURRENT_PLAN_VERSION}
              {current ? ` · ${current.label} · published ${dateOnly(current.publishedAt)}` : ""}
            </p>
          </div>
          <div className="flex items-center gap-1">
            <Button
              variant="outline"
              size="icon-sm"
              aria-label="Zoom out"
              onClick={() => setZoom((z) => Math.max(60, z - 10))}
            >
              <Minus className="size-4" />
            </Button>
            <span className="w-12 text-center text-sm tabular-nums text-muted-foreground">
              {zoom}%
            </span>
            <Button
              variant="outline"
              size="icon-sm"
              aria-label="Zoom in"
              onClick={() => setZoom((z) => Math.min(120, z + 10))}
            >
              <Plus className="size-4" />
            </Button>
          </div>
        </div>

        <Tabs defaultValue="plan">
          <TabsList>
            <TabsTrigger value="plan">Plan</TabsTrigger>
            <TabsTrigger value="rules">Rules · {CASE_RULES.length}</TabsTrigger>
            <TabsTrigger value="versions">Versions</TabsTrigger>
          </TabsList>

          <TabsContent value="plan" className="pt-4">
            {/*
              Zoom scales the board rather than the page, so the six-stage spine
              can be read end to end on a projector without shrinking the chrome.
            */}
            <div className="overflow-x-auto">
              <div
                className="flex origin-top-left flex-col gap-6"
                style={{ zoom: `${zoom}%` }}
              >
                <div>
                  <span className="mb-2 block text-sm font-medium text-muted-foreground">
                    Primary stages
                  </span>
                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">
                    {PRIMARY_STAGES.map((stage) => (
                      <StageCard key={stage.id} stage={stage} />
                    ))}
                  </div>
                </div>

                <div className="rounded-xl bg-muted/40 p-4">
                  <span className="mb-2 block text-sm font-medium text-muted-foreground">
                    Secondary stages · conditional paths
                  </span>
                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
                    {CONDITIONAL_STAGES.map((stage) => (
                      <StageCard key={stage.id} stage={stage} />
                    ))}
                  </div>
                </div>

                <div>
                  <span className="mb-2 block text-sm font-medium text-muted-foreground">
                    Terminal stages · exit the case without completing it
                  </span>
                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
                    {TERMINAL_STAGES.map((stage) => (
                      <StageCard key={stage.id} stage={stage} />
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
              {(["agent", "process", "human", "api"] as const).map((actor) => (
                <span key={actor} className="flex items-center gap-1.5">
                  <ActorChip actor={actor} />
                  <span className="capitalize">{actor}</span>
                </span>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="rules" className="flex flex-col gap-3 pt-4">
            <Card className="gap-1 p-5">
              <span className="text-base font-semibold">Rules decide how your case moves</span>
              <p className="text-sm text-muted-foreground">
                Rules are the conditions that control the case. They decide when stages and tasks
                start, complete, or exit, and the case agent reads them at run time to work out the
                next best action when no rule fully settles the question.
              </p>
            </Card>

            <div className="flex flex-wrap items-center justify-between gap-2">
              <ButtonGroup>
                {(["all", "v2"] as const).map((key) => (
                  <Button
                    key={key}
                    variant="outline"
                    size="sm"
                    onClick={() => setScope(key)}
                    className={cn(
                      "font-normal text-muted-foreground",
                      scope === key &&
                        "bg-primary/10 font-medium text-primary hover:bg-primary/10 hover:text-primary",
                    )}
                  >
                    {key === "all" ? "All rules" : "Added in v2"}
                  </Button>
                ))}
              </ButtonGroup>
              <Input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search rules"
                className="h-8 w-64 text-sm"
              />
            </div>

            <Card className="gap-0 overflow-hidden p-0">
              <div className="overflow-x-auto">
                <table className="w-full min-w-[62rem] text-sm">
                  <thead>
                    <tr className="border-b border-border bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground">
                      <th className="w-36 py-2.5 pl-4 pr-3 font-medium">Scope</th>
                      <th className="w-52 px-3 py-2.5 font-medium">Element</th>
                      <th className="w-40 px-3 py-2.5 font-medium">Rule</th>
                      <th className="w-48 px-3 py-2.5 font-medium">When</th>
                      <th className="w-52 px-3 py-2.5 font-medium">If</th>
                      <th className="px-3 py-2.5 font-medium">Then</th>
                      <th className="w-44 py-2.5 pl-3 pr-4 font-medium">Authored by</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rules.map((rule) => (
                      <RuleRow key={rule.id} rule={rule} />
                    ))}
                    {rules.length === 0 && (
                      <tr>
                        <td colSpan={7} className="px-4 py-8 text-center text-sm text-muted-foreground">
                          No rules match this filter.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </Card>
          </TabsContent>

          <TabsContent value="versions" className="flex flex-col gap-3 pt-4">
            <Card className="gap-3 p-5">
              <div className="flex items-center gap-2">
                <GitBranch className="size-4 text-muted-foreground" />
                <span className="text-base font-semibold">
                  {PLAN_CHANGELOG.from} → {PLAN_CHANGELOG.to}
                </span>
              </div>
              <p className="rounded-lg bg-muted/60 p-3 text-sm italic text-muted-foreground">
                “{PLAN_CHANGELOG.prompt}”
              </p>
              <ul className="flex flex-col gap-1.5">
                {PLAN_CHANGELOG.changes.map((change) => (
                  <li key={change.text} className="flex items-start gap-2 text-sm">
                    <span
                      className={cn(
                        "mt-0.5 font-mono text-xs",
                        change.kind === "added" ? "text-success" : "text-warning",
                      )}
                      aria-hidden
                    >
                      {change.kind === "added" ? "+" : "~"}
                    </span>
                    <span>{change.text}</span>
                  </li>
                ))}
              </ul>
              <span className="text-xs text-muted-foreground">{PLAN_CHANGELOG.summary}</span>
              <span className="text-xs font-medium">{PLAN_CHANGELOG.migrationNote}</span>
            </Card>

            <div className="flex flex-col gap-2">
              {[...CASE_PLAN_VERSIONS].reverse().map((version) => (
                <Card key={version.version} className="gap-1 p-5">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-base font-semibold">{version.version}</span>
                    <span className="text-sm text-muted-foreground">{version.label}</span>
                    {version.version === CURRENT_PLAN_VERSION && (
                      <span className="rounded-full bg-success/10 px-2 py-0.5 text-[11px] font-medium text-success">
                        Current
                      </span>
                    )}
                  </div>
                  <span className="text-xs text-muted-foreground">
                    Published {dateOnly(version.publishedAt)}
                  </span>
                  <p className="text-sm text-muted-foreground">{version.note}</p>
                </Card>
              ))}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </PageContainer>
  );
}
