// Case rules: the conditions that decide when stages and tasks start, complete,
// or exit. These are what the case agent reads at run time.
//
// Transcribed from the storyboard's Studio "Rules" view (scene 10) plus the
// SDD's stage entry/exit tables. Scene 11 adds the two v2 rows: the recurrence
// gate on Close and learn, and the routing change that points the
// recurrence-detected event at the new Product-quality escalation stage.

export type RuleScope = "Case" | "Stage" | "Sequential task" | "Event-driven task" | "Manually triggered";

export interface CaseRule {
  id: string;
  scope: RuleScope;
  element: string;
  rule: string;
  when: string;
  /** Guard expression. Empty when the rule fires unconditionally. */
  if?: string;
  then: string;
  /** Rules the coding agent generated rather than a reviewer authoring. */
  autoGenerated?: boolean;
  /** The reviewer this rule came out of, per storyboard scene 10. */
  authoredBy?: string;
  /** Case plan version this rule was introduced in. */
  since: "v1" | "v2";
}

export const CASE_RULES: CaseRule[] = [
  {
    id: "r01",
    scope: "Case",
    element: "Portal",
    rule: "Case entry",
    when: "Warranty claim submitted",
    then: "Enter case",
    since: "v1",
  },
  {
    id: "r02",
    scope: "Stage",
    element: "Intake and impact triage",
    rule: "Enter case",
    when: "Case entered",
    then: "Enter Intake and impact triage",
    since: "v1",
  },
  {
    id: "r03",
    scope: "Sequential task",
    element: "Assemble evidence (Agent)",
    rule: "Task entry",
    when: "Stage entered",
    then: "Enter Assemble evidence",
    autoGenerated: true,
    since: "v1",
  },
  {
    id: "r04",
    scope: "Sequential task",
    element: "Classify impact (Human)",
    rule: "Task entry",
    when: "Upstream task completed",
    then: "Enter Classify impact",
    autoGenerated: true,
    since: "v1",
  },
  {
    id: "r05",
    scope: "Stage",
    element: "Intake and impact triage",
    rule: "Stage complete",
    when: "Required tasks completed",
    then: "Complete Intake and impact triage",
    since: "v1",
  },
  {
    id: "r06",
    scope: "Stage",
    element: "Coverage and evidence review",
    rule: "Stage complete",
    when: "Required tasks completed",
    then: "Complete Coverage and evidence review",
    since: "v1",
  },
  {
    id: "r07",
    scope: "Stage",
    element: "Coverage and evidence review",
    rule: "Coverage ownership",
    when: "Stage entered",
    then: "Assign to Global Warranty Operations",
    authoredBy: "Priya Raghunathan",
    since: "v1",
  },
  {
    id: "r08",
    scope: "Event-driven task",
    element: "Engineering exception",
    rule: "Task entry",
    when: "New evidence uploaded",
    if: "estimate.scope !== approved.scope",
    then: "Enter Engineering exception",
    since: "v1",
  },
  {
    id: "r09",
    scope: "Stage",
    element: "Parts substitution review",
    rule: "Equivalence standard",
    when: "Alternate part proposed",
    if: "alternate.equivalenceEvidence === null",
    then: "Block approval until equivalence evidence is attached",
    authoredBy: "Kelsey Nordstrom",
    since: "v1",
  },
  {
    id: "r10",
    scope: "Stage",
    element: "Close and learn",
    rule: "Recurrence gate",
    when: "Tasks completed: Recurrence scan",
    if: "relatedFailures >= 4",
    then: "Enter Product-quality escalation",
    autoGenerated: true,
    authoredBy: "Ryan Ochoa",
    since: "v2",
  },
  {
    id: "r11",
    scope: "Stage",
    element: "Close and learn",
    rule: "Stage complete",
    when: "Required tasks completed",
    if: "recurrenceReviewed === true",
    then: "Complete Close and learn",
    since: "v2",
  },
  {
    id: "r12",
    scope: "Manually triggered",
    element: "Waiting for customer evidence",
    rule: "Entry rule 1",
    when: "Manual activation",
    then: "Enter Waiting for customer evidence",
    since: "v1",
  },
];

/** The v1 → v2 diff the coding agent applied, shown on the Case plans page. */
export const PLAN_CHANGELOG = {
  from: "v1",
  to: "v2",
  prompt:
    "Add a product-quality escalation gate before a case can close, if the recurrence check finds a pattern and it hasn't been reviewed.",
  changes: [
    { kind: "added" as const, text: "Stage added: Product-quality escalation (4 tasks)" },
    {
      kind: "updated" as const,
      text: 'Rule updated: Close and learn now requires "recurrence reviewed = true"',
    },
    { kind: "updated" as const, text: "Routing: recurrence-detected event now targets the new stage" },
  ],
  summary: "3 changes · 1 stage, 1 rule, 1 route · case plan version 1 → 2",
  migrationNote: "Running cases can be migrated onto v2 without restarting.",
};
